### ISSUE TITLE
FEATURE - Setup Project Storyboards & implement pods

### ISSUE THREAD

**Issue by MatthewFraser22** [MatthewFraser22/ios-DollarCostAveragingCalculator#3]
**TODO**
1. Implement two pods

- [x] Loaf - Custom toast messages
- [x] MBProgressHUD - Progress animation

3. 

- [x] Embed in Navigation Controller

2. Setup Storyboard and segues

- [x] Main Search Storyboard (UITableViewController)
- [x] Dollar Cost Calculator Storyboard (UITableViewController)
- [x] UITableViewController
